import type { Metadata, Viewport } from "next";
import { Space_Grotesk, Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import ScrollReveal from "@/components/ScrollReveal";

const SITE_URL = "https://e-biz.co.ke";

// Self-hosted via next/font, so no render-blocking external request and no FOUT.
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-space-grotesk",
  display: "swap",
});
const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-inter",
  display: "swap",
});
const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-jetbrains",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "E-biz — Ecommerce platform for online, in-store & WhatsApp",
    template: "%s · E-biz",
  },
  description:
    "Sell online, in-store and on WhatsApp from one dashboard — M-Pesa, Pesapal, Paystack, cards and cash built in. Managed hosting included, ships to 194 countries.",
  keywords: [
    "E-biz",
    "ecommerce platform",
    "online store builder",
    "sell on WhatsApp",
    "WhatsApp commerce",
    "M-Pesa online store",
    "Pesapal integration",
    "Paystack integration",
    "point of sale and online store",
    "multi-branch inventory",
    "multi-currency store",
    "ecommerce platform Kenya",
    "Shopify alternative",
    "WooCommerce alternative",
    "headless commerce",
    "REST API ecommerce",
  ],
  authors: [{ name: "E-biz", url: SITE_URL }],
  creator: "E-biz",
  publisher: "E-biz",
  applicationName: "E-biz",
  category: "technology",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: "E-biz",
    title: "E-biz — Sell online, in-store & on WhatsApp",
    description:
      "The all-in-one ecommerce platform: one dashboard for online, in-store and WhatsApp selling, with M-Pesa, Pesapal, Paystack, cards and cash built in.",
    // OG image is generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "E-biz — Sell online, in-store & on WhatsApp",
    description:
      "One dashboard for online, in-store and WhatsApp selling — M-Pesa, Pesapal, Paystack, cards and cash built in.",
    // Twitter image falls back to the generated opengraph-image
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: { canonical: SITE_URL },
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml" }],
    apple: "/favicon.svg",
  },
  // Google Search Console: set NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION to your
  // token (or verify via DNS / sitemap and leave this unset).
  verification: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION
    ? { google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION }
    : undefined,
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#FAFAF7" },
    { media: "(prefers-color-scheme: dark)", color: "#0E0E0C" },
  ],
};

const orgJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "@id": `${SITE_URL}/#organization`,
  name: "E-biz",
  legalName: "E-biz Ecommerce Management System",
  url: SITE_URL,
  logo: `${SITE_URL}/favicon.svg`,
  image: `${SITE_URL}/opengraph-image`,
  description:
    "Headless e-commerce platform for modern retailers. Sell online, in-store, and on WhatsApp.",
  email: "hello@e-biz.co.ke",
  slogan: "The commerce command center for modern brands.",
  areaServed: ["KE", "Worldwide"],
  address: {
    "@type": "PostalAddress",
    addressLocality: "Nairobi",
    addressCountry: "KE",
  },
  contactPoint: {
    "@type": "ContactPoint",
    contactType: "customer support",
    email: "hello@e-biz.co.ke",
    areaServed: "KE",
    availableLanguage: ["en"],
  },
};

const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  "@id": `${SITE_URL}/#website`,
  url: SITE_URL,
  name: "E-biz",
  description:
    "The headless commerce platform for modern brands. Sell online, in-store, and on WhatsApp.",
  inLanguage: "en",
  publisher: { "@id": `${SITE_URL}/#organization` },
};

const softwareJsonLd = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "E-biz",
  applicationCategory: "BusinessApplication",
  operatingSystem: "Web",
  url: SITE_URL,
  description:
    "A headless e-commerce platform with M-Pesa, Pesapal, Paystack, cards, bank transfer and Cash on Delivery built in. 20+ toggleable addons including multi-branch inventory, multi-currency, AI catalog, loyalty, subscriptions, REST API and WhatsApp commerce. Deployed on a managed dedicated server, hosting included.",
  featureList: [
    "Online store",
    "In-store point of sale",
    "WhatsApp commerce",
    "M-Pesa, Pesapal, Paystack, cards & cash",
    "Multi-branch inventory",
    "Multi-currency",
    "AI catalog & search",
    "Loyalty & subscriptions",
    "REST API & webhooks",
    "Managed dedicated hosting",
  ],
  provider: { "@id": `${SITE_URL}/#organization` },
  offers: {
    "@type": "Offer",
    price: "35",
    priceCurrency: "USD",
    description:
      "From USD 35 / KES 4,000 per month, with managed dedicated hosting included.",
    priceSpecification: {
      "@type": "UnitPriceSpecification",
      price: "35",
      priceCurrency: "USD",
      unitText: "MONTH",
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${spaceGrotesk.variable} ${inter.variable} ${jetbrainsMono.variable}`}
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html:
              "(function(){try{var t=localStorage.getItem('ebiz-theme');if(t==='dark'||t==='light'){document.documentElement.dataset.theme=t;}}catch(e){}})();",
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(orgJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareJsonLd) }}
        />
      </head>
      <body>
        {children}
        <ScrollReveal />
      </body>
    </html>
  );
}
