import type { Metadata, Viewport } from "next";
import "./globals.css";

const SITE_URL = "https://e-biz.co.ke";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "E-biz — The headless commerce platform for modern brands",
    template: "%s · E-biz",
  },
  description:
    "E-biz is a headless e-commerce platform for modern retailers. Sell online, in-store, and on WhatsApp — with M-Pesa, Pesapal, Paystack, cards, bank transfer, and cash built in. One calm dashboard for your whole operation, shippable to 194 countries.",
  keywords: [
    "E-biz",
    "headless commerce",
    "e-commerce platform",
    "online store builder",
    "WhatsApp commerce",
    "multi-branch inventory",
    "multi-currency store",
    "M-Pesa integration",
    "Pesapal integration",
    "Paystack",
    "Shopify alternative",
    "WooCommerce alternative",
    "REST API e-commerce",
  ],
  authors: [{ name: "E-biz", url: SITE_URL }],
  creator: "E-biz",
  publisher: "E-biz",
  applicationName: "E-biz",
  category: "technology",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: "E-biz",
    title: "E-biz — The headless commerce platform for modern brands",
    description:
      "Sell online, in-store, on WhatsApp — with M-Pesa, Pesapal, Paystack, cards, bank, and cash built in. The commerce command center for modern retail.",
    // OG image is generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "E-biz — The headless commerce platform for modern brands",
    description:
      "Sell online, in-store, on WhatsApp — every way your customers pay. One calm dashboard for your whole business.",
    // Twitter image falls back to the generated opengraph-image
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: { canonical: SITE_URL },
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml" }],
    apple: "/favicon.svg",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#FAFAF7" },
    { media: "(prefers-color-scheme: dark)", color: "#0E0E0C" },
  ],
};

const orgJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "@id": `${SITE_URL}/#organization`,
  name: "E-biz",
  legalName: "E-biz Ecommerce Management System",
  url: SITE_URL,
  logo: `${SITE_URL}/favicon.svg`,
  image: `${SITE_URL}/opengraph-image`,
  description:
    "Headless e-commerce platform for modern retailers — sell online, in-store, and on WhatsApp.",
  email: "hello@e-biz.co.ke",
  slogan: "The commerce command center for modern brands.",
  areaServed: ["KE", "Worldwide"],
  address: {
    "@type": "PostalAddress",
    addressLocality: "Nairobi",
    addressCountry: "KE",
  },
  contactPoint: {
    "@type": "ContactPoint",
    contactType: "customer support",
    email: "hello@e-biz.co.ke",
    areaServed: "KE",
    availableLanguage: ["en"],
  },
};

const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  "@id": `${SITE_URL}/#website`,
  url: SITE_URL,
  name: "E-biz",
  description:
    "The headless commerce platform for modern brands — sell online, in-store, and on WhatsApp.",
  inLanguage: "en",
  publisher: { "@id": `${SITE_URL}/#organization` },
};

const softwareJsonLd = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "E-biz",
  applicationCategory: "BusinessApplication",
  operatingSystem: "Web",
  url: SITE_URL,
  description:
    "A headless e-commerce platform with M-Pesa, Pesapal, Paystack, cards, bank transfer and Cash on Delivery built in. 20+ toggleable addons including multi-branch inventory, multi-currency, AI catalog, loyalty, subscriptions, REST API and WhatsApp commerce. Deployed on a managed dedicated server, hosting included.",
  featureList: [
    "Online store",
    "In-store point of sale",
    "WhatsApp commerce",
    "M-Pesa, Pesapal, Paystack, cards & cash",
    "Multi-branch inventory",
    "Multi-currency",
    "AI catalog & search",
    "Loyalty & subscriptions",
    "REST API & webhooks",
    "Managed dedicated hosting",
  ],
  provider: { "@id": `${SITE_URL}/#organization` },
  offers: {
    "@type": "Offer",
    price: "35",
    priceCurrency: "USD",
    description:
      "From USD 35 / KES 4,000 per month — managed dedicated hosting included.",
    priceSpecification: {
      "@type": "UnitPriceSpecification",
      price: "35",
      priceCurrency: "USD",
      unitText: "MONTH",
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap"
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(orgJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareJsonLd) }}
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
